---
- name: create Docker container
  hosts: x
  become: yes

  tasks:
    - name: create Docker hello-world container
      docker_container:
        name: hello-world
        image: hello-world
        state: started
      
