---
- name: Install Docker
  hosts: test
  become: yes
  tasks:
    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: "present"