---
- name: Install docker-py 
  hosts: np
  become: yes

  tasks:
    - name: Install python3
      apt:
        name: python3
      become: yes
      
    - name: Install python3-pip
      apt:
        name: python3-pip
      become: yes
    # - name: Cheating cmd
    #   shell: pip3 install docker docker-compose