---
- name: Install docker-py 
  hosts: frank157
  become: yes

  tasks:
    - name: Install python3
      apt:
        name: python3
      become: yes
      
    - name: Install python3-pip
      apt:
        name: python3-pip
      become: yes